# Configuration

#The message must match this format to the calculator to work.
enabled_by_default: true
format: "%expression%="
sound_success: "BLOCK_NOTE_BLOCK_PLING;1;1"
sound_error: "BLOCK_NOTE_BLOCK_BASS;1;1"